stages:
  - build
  - test
  - deploy

# Etapa de Build
build:
  image: openjdk:17
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/
  only:
    - main

# Etapa de Testes
test:
  image: openjdk:17
  stage: test
  script:
    - ./gradlew test
  only:
    - main

# Etapa de Deploy
deploy:
  image: docker:latest
  stage: deploy
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $AWS_ECR_URI/$IMAGE_NAME:latest
    - docker push $AWS_ECR_URI/$IMAGE_NAME:latest
  only:
    - main
