name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Faça o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configure o JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt' # Ou 'zulu', dependendo do seu JDK

      # Passo 3: Configure o Gradle cache
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Passo 4: Execute o build
      - name: Build with Gradle
        run: ./gradlew build

      # Passo 5: Execute os testes
      - name: Run tests
        run: ./gradlew test
